apiVersion: v1
kind: Service
metadata:
  name: ghost-blog
spec:
  ports:
  - port: 2368
    protocol: TCP
    targetPort: 2368
  selector:
    app: ghost-blog
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ghost-blog
  name: ghost-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-blog
  template:
    metadata:
      labels:
        app: ghost-blog
    spec:
      volumes:
      - name: ghost-content
        persistentVolumeClaim:
          claimName: ghost-content
      containers:
      - image: ghost:alpine
        name: ghost-blog
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http://blog.demo.azure.boxboat.io
        volumeMounts:
        - mountPath: "/var/lib/ghost/content"
          name: ghost-content
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ghost-blog
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: blog.demo.azure.boxboat.io
    http:
      paths:
      - backend:
          serviceName: ghost-blog
          servicePort: 2368
        path: /
        pathType: Prefix
