apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: hello-world
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello-world
  name: hello-world
spec:
  containers:
  - image: boxboat/hello-world
    name: hello-world
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: hello-world.demo.azure.boxboat.io
    http:
      paths:
      - backend:
          serviceName: hello-world
          servicePort: 80
        path: /
        pathType: Prefix
